### ISSUE TITLE
Add the resources Section

### ISSUE THREAD

**Issue by swilgosz** [markets/awesome-ruby#1077]
### Overview

Inspired by https://github.com/sindresorhus/awesome-nodejs I'm wondering if you'd be interested in adding the resources section, listing active blogs/tutorials or courses about Ruby?

### Suggestion
- Wrap all libraries under the `Projects` top-level header.
- Add the `Learning Resources` section below.

**Comment by markets** [comment]
Hi @swilgosz 👋🏼 

Unfortunately we are not really interested right now, we had that section in the past but we finally removed due to maintenance costs. So now, as most of the `awesome-*` projects, we focus on libraries, apps, tools. 

Maybe those kind of links fit better in other lists like https://github.com/dreikanter/ruby-bookmarks?

**Comment by swilgosz** [comment]
Thanks for the insanely quick response! And for the tip!

I understand your point, so it seems this issue can be closed:)

**Comment by markets** [comment]
Yes! It would be nice to have that "Learning Resources" section, but at the end everybody was proposing their blog, book, course... and it's hard to draw the line for that kind of resources. At least for libraries, we have GitHub stars, RubyGems downloads...

**Comment by swilgosz** [comment]
Got your point. 

Maybe I could come up with such list, having a clear contribution requirement, as the issue is exactly that - those lists tend to be not maintained :(.
