### ISSUE TITLE
Add ros-apartment to Multi-tenancy

### ISSUE THREAD

**Issue by hoshy** [markets/awesome-ruby#1128]
[ROS Apartment](https://rubygems.org/gems/ros-apartment) - Allows Rack applications to deal with database multitenancy through ActiveRecord

**Comment by markets** [comment]
Hey @hoshy! I think we already have this resource under https://github.com/markets/awesome-ruby?tab=readme-ov-file#ormodm-extensions, in the "Multi-tenancy" sub-section. Is this like the new maintained fork?

**Comment by hoshy** [comment]
Hi @markets, you don't. It's another implementation of it.

https://github.com/influitive/apartment (the one you have) vs.  https://rubygems.org/gems/ros-apartment (the new one)

**Comment by markets** [comment]
Since Rails 6 there is "native" way to implement sharding: https://guides.rubyonrails.org/active_record_multiple_databases.html#horizontal-sharding. So probably that's the reason of both gems being ~abandoned. I'd like to keep current one for historical reasons, but maybe adding this fork is not necessary/relevant anymore?
