### ISSUE TITLE
Add Sail dashboard

### ISSUE THREAD

**Issue by vinistock** [markets/awesome-ruby#881]
Hello, folks

I'd like to suggest the addition of [Sail], an admin panel for managing configuration settings on a live Rails app. It is supposed to be a powerful, yet light weight, toolkit for configuring a Rails app on the fly without requiring a deploy.

It is a project that I am actively maintaining and that has been featured in [Ruby Weekly]. Let me know your thoughts and if people like it I can open a pull request adding it.

[Ruby Weekly]: https://rubyweekly.com/issues/422
[Sail]: https://github.com/vinistock/sail

**Comment by markets** [comment]
Cool project @vinistock :+1: 

Would you like to submit a PR?

**Comment by markets** [comment]
Hi @vinistock 

> If it's too fresh for the list, are you just going to leave the PR open until it has more downloads?

Yes, I'd leave it open until the project reaches some maturity, as we usually do for all "fresh" resources. So yes, maybe make sense to wait some time... but PRs are, in general, more user friendly... since we provide a PR template to fill useful data about the project, the people can vote easily without having to navigate to other pages. Up to you! 

Thanks for sharing anyway!

**Comment by vinistock** [comment]
@markets I will put together a pull request then! Which category do you believe it would fit?

**Comment by markets** [comment]
:+1: I think it should be under https://github.com/markets/awesome-ruby#configuration
