### ISSUE TITLE
Add roots to Scientific

### ISSUE THREAD

**Issue by jzakiya** [markets/awesome-ruby#894]
`roots` is Rubgem with 2 methods to find all the nth roots (real and complex) of any number (real and complex), and also 2 methods to find all the nth roots of integers. Makes these operations simple to perform with a consistent syntax.

https://github.com/jzakiya/roots
https://rubygems.org/gems/roots
https://www.scribd.com/doc/60067570/Roots-in-Ruby

**Features**
- fast
- accurate
- easy to use

**Comment by markets** [comment]
Hi @jzakiya and thanks for sharing your projects! Unfortunately, I think we can't consider it essential Ruby or widely popular projects in the community (~8k downloads in ~6 years).

**Comment by jzakiya** [comment]
Hey, thanks for responding.

Let me address why I think the `roots` gem needs to be included under the category Scientific.

First, by definition, applications and tools used in math, science, and engineering, and other technology fields in general, should not be expected to garner the level of use and appeal things that Ruby is most known for, like web development, achieves.  So saying `roots` has been downloaded only ~8800 times is a negative is a misunderstanding of the expected user base for it. You should actually be thinking, Wow, it's gotten that many downloads because 8800+ people found it useful for the utility it provides in the niche domain it's intended to serve.

Also, if you do not understand what problems `roots` fixes in Ruby (and it fixes some very specific problems Ruby has doing certain math), and you never do math and science in those domain spaces, you also can't appreciate its usefulness and utility. Which begs me to ask, did you go to its homepage and read what it does and how it works? and tried to use it?  https://github.com/jzakiya/roots

`roots` follows the Unix tradition of apps|utilities being focused to perform a very specific task, and in this case also, to correct errors in a few specific math operations. And it does that job well, which is why it **has** been downloaded as much as it has.

I first released `roots` in 2009, and after much effort, finally got Ruby to include in 2.5 the method `Integer.sqrt`. (https://medium.com/@atul9/using-ruby-2-5s-new-integer-sqrt-cd9cb5955e12) I'm now trying to get the other methods in the gem included too, because they didn't fix all of those classes of math operations by just including `Integer.sqrt`.  You can see that ongoing effort here: https://bugs.ruby-lang.org/issues/15571

When I look at sites such as `Awesome-<whatever language>` the first thing I look for is **what function does the app perform, problems it solves|improves, and its possible usefulness to me.**  I only look at downloads to guage how many people have used it, but that has to be taken in the context of the relative age differences between apps, and other comparison parameters.

I would think if you're not involved in a certain field, or domain of knowledge, you have no objective basis to judge things in that field, so you would then ask people in those fields for their assessments of apps, etc.  An `awesome ruby` is one that does something useful (solves some problem, or provides new, unique, or useful utility), is well documented, and easy to use. These are the metrics I use to make that decision on what to use.  

I noticed the number of downloads for some of the apps in the Scientific category have a comparable level of downloads as `roots` but aren't as well documented as mine, so if downloads seems to be the only thing mentioned to disqualify it that seems very arbitrary.

Finally, for people who work in the fields of math, science, algorithm development, etc `roots` is essential to fix some math operations problems Ruby has they may not even be aware exist, while providing functionality and ease of use not currently present in Ruby.  And for that alone, `roots` is `awesome` and should be included.

**Comment by markets** [comment]
Hi @jzakiya and thanks for such an accurate explanation now, it would have helped if had been like that from from the beginning :). As much info you provide in your initial request, the better for the community participating here in Awesome Ruby. 

> Wow, it's gotten that many downloads because 8800+ people found it useful

This is not 100% true, that's 8800 downloads, not 8800 different people. Downloads aren't the only thing I check to make a decision, but it gives us a reference. 

> did you go to its homepage and read what it does and how it works? and tried to use it?

Yep, I read what it does and took a look at the code in GitHub, but of course, I can't try or analyze in depth all suggestions made in Awesome Ruby, I need help from all the community around. That's why I didn't close it, I just leave my initial thoughts and leave the issue open for the people to drop their feedback (reactions, comments) and continue the discussion.

---

The scientific section has been introduced here: https://github.com/markets/awesome-ruby/pull/165, so it was basically an import from [this gist](https://gist.github.com/agarie/272ef4967479fedac856).

Sorry, at the end, it's not easy to draw the line in these kind of projects, so that's why I never close issues at first, I prefer to give my first impressions/thoughts, and then continue with a constructive discussion with the goal of merging or closing the request. If you read other issues and pull-requests in this repository, you'll see a lot of interesting discussions about this topic. I'm just trying to do my best maintaining this list for years (from Jun 29, 2014). 

That said, and after reviewing the links you provided above, I think `roots` and `prime-utils` both have a place under the `Scientific` category. But please, try to understand we have limited time for open source work (so I've to distribute it with the rest of projects I also maintain).
