### ISSUE TITLE
Remove outdated / unmaintained repos

### ISSUE THREAD

**Issue by thefabbulus** [markets/awesome-ruby#988]
Some examples, just from the first ~30 repos listed:

- https://github.com/typus/typus (Latest commit on 15 Sep 2016, 47 open issues, 15 open PRs)
- https://github.com/jkrall/analytical (Latest commit on 22 Oct 2014, 5 open issues, 6 open PRs)
- https://github.com/hybridgroup/gabba (Latest commit on 22 May 2014, 8 open issues, 1 open PR)
- https://github.com/apotonick/apotomo (Latest commit on 2 Oct 2015, 25 open issues, 7 open PRs)

So, as per [Quality Standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard): "**_Actively maintained (even if that just means take care of open issues and/or keep compatibility with current Ruby versions)._**" maybe they should be removed, also due to probable conflicts/deprecations with latest Ruby versions.

Maybe something like [this](https://stackoverflow.com/a/50204589/1033737) could be useful to write a script in order to get the latest commit date for all the repos listed in `
awesome_ruby` and decide if it's worth it to remove them.

**Comment by markets** [comment]
Thanks for the heads up @thefabbulus! 

Yep, we should remove non actively maintained projects, but not sure about automation... Sometimes it's hard to decide based on latest commit, there is a lot of edge cases: "finalized" projects, issues than can't be closed because are just feature requests, ... 

I think most of `awesome-*` lists are manually maintained by the community (even https://github.com/sindresorhus/awesome), because at the end, some human needs to check it and decide. I think I'd prefer to stick with this approach for now: https://github.com/markets/awesome-ruby/pulls?q=is%3Apr+is%3Aclosed+label%3Aremoval 

But in case you detect any project that really needs to be removed from the list, please send a PR :)

![automation](https://user-images.githubusercontent.com/576701/80868095-a89cfe00-8c98-11ea-9567-f981df72832a.png)
